### ISSUE TITLE
Compare with Qwen2-VL

### ISSUE THREAD

**Issue by SushantGautam** [PKU-YuanGroup/LLaVA-CoT#2]

**Comment by XuGW-Kevin** [comment]
Great issue! Sorry for the overlook of Qwen2-VL.
Qwen2-VL is strong; we have no reason not to compare.
We're going to release a model trained on Qwen2-VL in 2-3 weeks.

However, if you really want to know the performance of Qwen2-VL-7B on our reasoning benchmark now, I can give you the answer: 65.85. Our LLaVA-o1(Llama-3.2-11B-Vision) is 65.8.
Our LLaVA-o1(Llama-3.2-11B-Vision) is worse than Qwen2-VL-7B. This is correct.
However, we must point out that Qwen2-VL-7B used huge amounts of training data (at least millions, I believe) and we only used 100k.
Also, **our method is suitable for any existing VLMs including Qwen2-VL.** We will publish a model trained on Qwen2-VL soon.
Stay tuned!

**Comment by Elenore1997** [comment]
> Great issue! Sorry for the overlook of Qwen2-VL. Qwen2-VL is strong; we have no reason not to compare. We're going to release a model trained on Qwen2-VL in 2-3 weeks, and update our paper by that time.
> 
> However, if you really want to know the performance of Qwen2-VL-7B on our reasoning benchmark now, I can give you the answer: 65.85. Our LLaVA-o1(Llama-3.2-11B-Vision) is 65.8. Our LLaVA-o1(Llama-3.2-11B-Vision) is worse than Qwen2-VL-7B. This is correct. However, we must point out that Qwen2-VL-7B used huge amounts of training data (at least millions, I believe) and we only used 100k. I think the most important thing is our model has significant improvements over Llama-3.2-Vision-Instruct because one can always switch to a stronger base model (like Qwen2-VL) and use more data (scale up the dataset).
> 
> To prove this, we will publish a model trained on Qwen2-VL soon. Stay tuned!

Great job! I would like to ask that how the LLaVA-O1 model and the O1 model based on Qwen2VL perform on Chinese language-image reasoning / understanding tasks? Thanks in advanced!

**Comment by zhangfaen** [comment]
+1 for comparition with Qwen-VL 2

**Comment by XuGW-Kevin** [comment]
> +1 for comparition with Qwen-VL 2

Thanks for your interest! @zhangfaen 
We're making progress on this. We'll release the comparison within a week.

**Comment by ankitdotpy** [comment]
> Great issue! Sorry for the overlook of Qwen2-VL. Qwen2-VL is strong; we have no reason not to compare. We're going to release a model trained on Qwen2-VL in 2-3 weeks, and update our paper by that time.

Hi @XuGW-Kevin 
I was wondering if there have been any updates on the model release that you mentioned. I would love to contribute to the project. Please let me know if there are opportunities to contribute or engage further.

**Comment by XuGW-Kevin** [comment]
> > Great issue! Sorry for the overlook of Qwen2-VL. Qwen2-VL is strong; we have no reason not to compare. We're going to release a model trained on Qwen2-VL in 2-3 weeks, and update our paper by that time.
> 
> 
> 
> Hi @XuGW-Kevin 
> 
> I was wondering if there have been any updates on the model release that you mentioned. I would love to contribute to the project. Please let me know if there are opportunities to contribute or engage further.

Yeah we've trained such a model on Qwen2-VL-7B-Instruct, and tested a few benchmarks. We find that while the performance on some benchmarks improves, the performance on other benchmarks becomes worse. The overall performance doesn't improve too much. I suspect that Qwen actually used the training questions in AI2D, ScienceQA, etc. Therefore, if we further finetune Qwen, the model will overfit to these questions. I'm not sure whether my suspicions are reasonable, and I think perhaps finetuning on the base Qwen model may help with this issue. I'm also happy to hear about any ideas you have!

**Comment by anirao2611** [comment]
Hello, is the finetuned Qwen-VL model released? I was trying to use the CoT dataset to finetune a Qwen3 model, wanted to see if there's already something. Thank you for the amazing work!

**Comment by XuGW-Kevin** [comment]
Hi @anirao2611, it is an honor to see that you are still interested in this work more than a year after its release. 

Simply put, we won't release a finetuned Qwen-VL model because we found that the Qwen-VL model was trained internally using high-quality, closed-source CoT data, and its domain likely already covers the problem domain of the LLaVA-CoT dataset. Therefore, training again with our open-source LLaVA-CoT dataset would not yield better results. 

It is also worth pointing out that VLM has developed very rapidly over the past year; in particular, the Qwen3-VL model already possesses _thinking_ capabilities, and its performance and reasoning abilities far exceed the GPT-4o we used when creating the dataset. 

Therefore, as an author, although I very much hope to see the community's attention and adoption of our work, I kindly suggest that if you need to finetune a Qwen3-VL model, you may consider newer datasets. However, I personally feel that the pure reasoning ability of Qwen3-VL is already very strong, and almost all open-source multimodal datasets may find it difficult to achieve better results.
