### ISSUE TITLE
More detailed information about constructing dataset similar to LLaVA-o1-100k.

### ISSUE THREAD

**Issue by ljqiang17** [PKU-YuanGroup/LLaVA-CoT#5]
Hi！Great work! We are also trying to give MLLM stronger reasoning abilities. Can you tell us more details about generating data? For example, how do you prompt GPT-4o?

**Comment by XuGW-Kevin** [comment]
Sure we will! We'll update the implementation details in 2~3 days.

**Comment by sugarandgugu** [comment]
waiting for details

**Comment by ljqiang17** [comment]
Hi, is there any update about the the implementation details of constructing dataset?

**Comment by XuGW-Kevin** [comment]
I've just uploaded the code to generate the dataset. I hope it helps!  (However, our dataset has not been made public yet. This is mainly because the images are quite large, and we are still checking whether it is permissible to include the image data directly in the dataset or if we should provide download links instead.)
